services:
  - type: web
    name: aegis-api
    env: docker
    plan: free
    region: singapore
    dockerContext: aegis_backend
    dockerfilePath: DockerFile
    healthCheckPath: /api/health-check
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: aegis-db
          property: connectionString
      - key: REDIS_URL
        sync: false # Set this value manually from Upstash
      - key: APP_NAME
        value: "AEGIS Defense System [RENDER]"

databases:
  - name: aegis-db
    plan: free